### ISSUE TITLE
Home URL is broken 404

### ISSUE THREAD

**Issue by jeremydouglass** [30-seconds/30-seconds-of-interviews#166] opened 2019-08-19 23:48 UTC
The URL linked from the repo head and the readme -- https://30secondsofinterviews.org -- is 404 on GitHub Pages.

**Comment by fejes713** [comment] 2019-08-23 18:46
Thanks for letting us know! I'll investigate right now! Sorry for the delay

**Comment by fejes713** [comment] 2019-08-23 19:43
The issue is fixed now 👍 Huge thanks to @jeremydouglass for pointing this out ❤️and sorry for a 4-day delay, my bad.

Since we're here, could you share where you heard about this project and is it useful to you? We're planning a second version with much more questions, new design, better performance, dark mode etc.

What are some things that you would love to see?

**Closed** 2019-08-23 20:20 UTC
